language: cpp
sudo: required
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - libcurl-dev
    sources:
      - george-edison55-precise-backports
script: ./configure && cmake --build build
