language: cpp
os:
  - linux
  - osx
env:
  - BUILD_TYPE=DEBUG
  - BUILD_TYPE=RELEASE
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - libboost-all-dev
      - g++-4.8
      - libstdc++-4.8-dev
      - clang-3.6
      - libgtest-dev
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
install:
  - cp -r /usr/src/gtest .
  - cd gtest
  - cmake .
  - make
  - ls -Rlah .
  - make DESTDIR="${TRAVIS_BUILD_DIR}" install
  - cd "${TRAVIS_BUILD_DIR}"
script: ./configure -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && make -Cbuild
