language: python
sudo: required
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - libcurl4-openssl-dev
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
install:
  - sudo apt-get install libcurl3-dev
script: ./configure && cmake --build build
