language: cpp
os:
  - linux
  - osx
env:
  - BUILD_TYPE=DEBUG
  - BUILD_TYPE=RELEASE
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - libboost-all-dev
      - g++-4.8
      - libstdc++-4.8-dev
      - clang-3.6
      - libgtest-dev
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
script: ./configure -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && make -Cbuild
