language: cpp
addons:
  apt:
    packages:
      - cmake
      - cmake-data
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
install:
  - POLLY_VERSION="0.6.2"
  - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
  - tar xf "v${POLLY_VERSION}.tar.gz"
  - export PATH="`pwd`/polly-${POLLY_VERSION}/bin:${PATH}"
script: ./configure && cmake --build build
