language: cpp
env:
  - BUILD_TOOLCHAIN=default
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - libboost-all-dev
      - ninja-build
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
install:
  - POLLY_VERSION="0.6.2"
  - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
  - tar xf "v${POLLY_VERSION}.tar.gz"
  - export POLLY_ROOT="`pwd`/polly-${POLLY_VERSION}"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"
script: ./configure -DCMAKE_TOOLCHAIN_FILE=${POLLY_ROOT}/${BUILD_TOOLCHAIN}.cmake -GNinja && ninja -Cbuild
